### ISSUE TITLE
Cadastro de usuario ambiente de homologação

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2017.2-Receituario-Medico#184]
Email de confirmação de cadastro (no ambiente de homologação) redireciona para um endereço localhost:

http://localhost:8000/user/confirm/8aa69b5a5dfccac2ef371bac4c94906cdbdbfc48

**Comment by thiagonf** [comment]
Esqueci de avisar, mas isso já foi solucionado no mesmo dia que foi reportado.
