### ISSUE TITLE
Feedback e sugestões

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2017.2-Receituario-Medico#98]
O projeto está bem facil de monitorar! Está todo o processo bem evidenciado (planejamento, monitoramento, controle, práticas ágeis)

- [x]  Criar um pacote de release por sprint, detalhando as principais entregas de valor (features entregues). Além de facilitar o rastreio  do trabalho de vcs, dá muita transparência. 

- [x]  Falta o project description no projeto de vcs.. :paintbrush: Deem uma olhada no checklist de projetos de software livre (essa aba tem vários outras informações interessante sobre o projeto de vcs)
https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/community

- [x]  Pensem em avançar as responsabilidades no projeto, e integrar MDS:
https://opensource.guide/leadership-and-governance/

- [x] Evitem retrabalho - sugestão: ao invés de criar uma issue para uma história e copiar a mesma história na wiki (como estão fazendo agora), na ultima faça apenas referencia (link) à issue 

- [x] Melhorar a motivação da equipe - trabalhem os ganhos épicos do trabalho que vcs estão fazendo! não só técnico, portfólio, mas também de impacto do trabalho de vocês :100: 

http://www.claudiamelo.org/2016/11/25/principios-gestao-agil/

- [x] Foquem no lean - minimizar desperdício (tenho a impressão que o problema de motivação as vezes é muito mais cansaço). Tentem identificar atividades/tarefas que estão fazendo que podem ser eliminadas..

**Comment by joaopaulonsoares** [comment]
@RochaCarla Tarefas que podem ser eliminadas: a matéria dela

**Comment by joaopaulonsoares** [comment]
Carla uma dúvida, sobre a parte de integrar MDS nas responsabilidades no projeto. Que responsabilidades você acha mais interessante para isso? Afinal não conseguimos observar muitas responsabilidades além de desenvolvimento que MDS possa desempenhar.

**Comment by RochaCarla** [comment]
@joaopaulonsoares, uma boa forma de nivelar o conhecimento em relação à metodologia é delegar para parte do time (MDS) tarefas/atividades relacionadas ao tracking (coleta de métricas, coleta de indicadores, registro dos dados na wiki). É uma forma de fortalecer a compreensão da metologia, aproximar o time de desenvolvimento com questões de gestão do projeto.
